config/routes.rb
Rails.application.routes.draw do

  root 'nodes#index'
  get 'node/:name' => 'nodes#show', as: 'node'
  post 'node/:name' => 'nodes#show'

end

app/models/pageview.rb
class Pageview < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :get_params
  before_action :save_pageview

  def index
  end

  def show
    render "#{@name}.html.md"
  end

  private

  def get_params
    hash = {
        "barbie_1" => -1,
        "barbie_3" => +1,

        "second_grade_1" => -1,
        "second_grade_3" => +1,

        "teams_1" => -1,
        "teams_3" => +1,

        "running_1" => -1,
        "running_3" => +1,

        "fat_1" => -1,
        "fat_3" => +1,

        "basketball_melody_1" => -1,
        "basketball_melody_3" => +1,

        "basketball_melody_1_1" => -1,
        "basketball_melody_1_3" => +1,

        "college_1" => -1,
        "college_3" => +1,

        "promotion_1" => -1,
        "promotion_3" => +1,
    }.with_indifferent_access

    @score = 0
    if controller_name == "nodes" and action_name == "index"
      @chain = []
    elsif controller_name == "nodes" and action_name == "show"
      @name = ActionController::Base.helpers.sanitize(params[:name])
      chain =  ActionController::Base.helpers.sanitize(params[:chain])
      if chain.blank?
        Pageview.create(controller_name: controller_name, action_name: action_name, session_id: session.id, data: {error: "blank chain", chain: @chain, score:@score})
        #flash[:danger] = "There has been an error, please start over."
        #redirect_to root_path
      end

      @chain = chain.blank? ? [] : JSON.parse(chain)
      # puts "@name is #{@name}"
      # puts "old @chain is #{@chain}"
      # puts "old @score is #{@score}"
      @chain << @name

      @chain.each do |n|
        delta = hash[n.parameterize.underscore.to_sym]
        @score += delta if delta
      end
      # puts "new @chain is #{@chain}"
      # puts "new @score is #{@score}"
    end
  end

  def save_pageview
    Pageview.create(controller_name: controller_name, action_name: action_name, session_id: session.id, data: {chain: @chain, score:@score})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/layouts/_flash_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<%# bootstrap alert types: success, info, warning, danger %>
<%# devise uses: alert, notice so we translate these to bootstrap typesaa %>
<% flash.each do |name, msg| %>
    <% name = "success" if name == "notice" %>
    <% name = "danger" if name == "alert" %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash-#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_pictures.html.erb
<div class="pictures-row">
  <% for idx in list do %>
      <span class="pictures-cell">
        <%= image_tag "med#{idx}.jpg", height:200 %>
      </span>
  <% end %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GenderQuest</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery? %>
</head>
<body>
<% list = (1..14).to_a %>
<%= render 'layouts/pictures', list: list[0..7] %>
<main class="container">
  <br><br><br>&nbsp;
  <div id="flash-messages">
    <%= render 'layouts/flash_messages' %>
  </div>

  <div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>
  <hr>
  <div class="footer-menu">
    <%= link_to "Start Over", root_path, data: { confirm: "Start Gender Quest over from the beginning?" } unless (controller_name == "nodes" and action_name == "index") %>
    <%= link_to "Credits", node_path("credits") %>
    <%= link_to "Contact", "mailto:genderquest@charlottepalmer.com?subject=Gender Quest" %>
  </div>
  <div class="social-container">
    <div class="links">
      <a href="#" title="Share on Facebook" data-type="facebook" data-url="http://genderquest.herokuapp.com" data-title="Gender Quest." data-description="A seventh grader at Menlo School made this 'choose your own adventure' style site about gender bias." class="prettySocial fa fa-facebook"></a>
      <a href="#" title="Share on Twitter" data-type="twitter" data-url="http://genderquest.herokuapp.com" data-description="A seventh grader at Menlo School made this 'choose your own adventure' style site about gender bias." class="prettySocial fa fa-twitter"></a>
      <a href="mailto:?subject=gender bias&body=%0D%0AA seventh grader at Menlo School made this 'choose your own adventure' style site about gender bias:%0D%0A%0D%0Ahttp://genderquest.herokuapp.com/%0D%0A%0D%0A" title="Share via Email" class="fa fa-envelope"></a>
    </div>
    <script type="text/javascript" class="source">
      $('.prettySocial').prettySocial();
    </script>
  </div>
</main>
<%= render 'layouts/pictures', list: list[7..14] %>
</body>
</html>

app/views/layouts/nodes.html.erb
<script>
  var score = <%= defined?(@score) ? @score : 0 %>;
  var chain = JSON.parse('<%= raw(@chain.to_json) %>');
</script>

<% content_for :content do %>
    <% if true or Rails.env.development? %>
        <% if action_name != "index" and (params[:name] != "credits") %>
            <br>
            <div class="score" %>
              <div id="scores">Melody's empowerment score: <%= @score %> </div>
              <!--<div id="chain">Chain: <%#= @chain %></div>-->
            </div>
            <br>
        <% end %>
    <% end %>
    <div class="node-markdown">
      <%= yield %>
    </div>
    <br>
<% end %>
<%= render template: "layouts/application" %>